### ISSUE TITLE
What's the most difficult part about running a large open source project like ESLint?

### ISSUE THREAD

**Issue by sindresorhus** [nzakas/ama#10]

**Comment by nzakas** [comment]
Issue triage, for so many reasons! 

First, the volume of incoming issues can be overwhelming. I can't ignore the project for a couple days because then I have to wade through a ton of issues to get caught up. So it has to be done pretty much daily.

Second, most issues don't have enough information to be able to respond. This is partly because GitHub issues don't let you prefill the description. In any case, my first reply to most issues is asking for standard info like what version someone is using, what code they're using, what options they're using.

Third, there are a lot of people who make feature requests, and for the most part, it's to solve a personal problem. They have given little thought to how the change would affect others out for with the project as a whole. They don't understand why we just don't accept what they're offering and sometimes get angry and mean as a result. That can be exasperating.

Last, there are way more issues than there are people to work on them. And since everyone is helping in their spare time, sometimes it can take a while for things to get done.
