### ISSUE TITLE
Why JavaScript?

### ISSUE THREAD

**Issue by peterpme** [nzakas/ama#19]
What is it about JS that made you wander into this realm? Is there another language you'd potentially switch to (full time)?

**Comment by nzakas** [comment]
When I started (2000), JavaScript was a great unknown. There were only a handful of books and very few materials to learn from. I really enjoyed it, and was intrigued about why such a unique language was so lacking in good instruction and documentation. To me, it was like discovering a new planet and being the first to start analyzing what was there. This is what eventually led me to write the first edition of Professional JavaScript, it was a record of everything I had learned on that new planet. I had to reason out through experimentation how things like prototypes worked because there was no real explanation available. JavaScript was a mystery I was determined to solve. Two publishers turned down that book because they said the market was too small. Fortunately for me and my career, the market grew. :)

The one other language I've really enjoyed is C#, and if I was forced to choose another language to work with, C# would be my choice. I just found it to be a really well-defined language that made a lot of things simple.
