### ISSUE TITLE
What aspect of collaborating with other JS devs you still find challenging? 

### ISSUE THREAD

**Issue by lozandier** [nzakas/ama#21]

**Comment by nzakas** [comment]
There are a lot of people with opinions, but few with the experience to validate those opinions. As someone with experience building large, highly-trafficked sites, I find it challenging to entertain the opinions when I know they are based more on personal and side projects because I know that the approach doesn't scale.

I also find it hard to deal with the onslaught of new and shiny things people want to use simply because they are new and shiny. When you're dealing with a business, rather than your own personal site, it typically doesn't pay to be an early adopter, and it almost always costs.
