### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [nzakas/ama#3]

**Comment by nzakas** [comment]
When I was in elementary school, my parents bought an Apple IIe clone for the house (the real Apple IIe's were too expensive for us), and I discovered that if I turned the computer on without a disk in the drive, it would boot to BASIC. My dad had taken a course on BASIC, so he had a manual, and I used that to make some really dumb programs. At the time, I was really into professional wrestling, so I made a program that simulated a match between two characters of your choosing. Then, it would go move by move, asking you what to do next. The match would never end because I couldn't figure out how to do that, but I was pretty happy.

After that, I was hooked.
