### ISSUE TITLE
What skills have made the biggest impact on your programming?

### ISSUE THREAD

**Issue by titoesteves** [nzakas/ama#50]
What topics, skills, learnings, etc, would you say have made you a better and more confident developer? As a follow up, what topics, skills, learnings, would you give to someone who wants to become a better overall developer?

**Comment by nzakas** [comment]
The most important thing is just to stay humble. Don't assume you know everything, approach every project and different idea with a spirit of curiosity, don't rush to judgement on things that aren't done the way you think they should be. Not needing to be right has done me more good in my career than anything else.

In addition, invest in learning design patterns and concepts rather than languages and technologies. Patterns and concepts are always useful while languages and frameworks will change many times during your career.
